### PR TITLE
Ensure pods are deleted before removing replication controller

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by grs** [comment]
Is this necessary or even desired? The replication controller should restart deleted pods anyway, right? Deleting the controller automatically deletes all the pods.

**Comment by lulf** [comment]
I observed that when removing an address, the replication controller was removed, but not the pod. And when I recreated the controller, it didn't recreate the pod because it was already there. And according to https://github.com/kubernetes/kubernetes/issues/103, its a feature.

**Comment by lulf** [comment]
Maybe its something special when doing it in the REST api

**Comment by grs** [comment]
So you delete the pods by scaling down to 0? And then delete the controller?

**Comment by lulf** [comment]
@grs yes, that is essentially it. I need to investigate some more if this is a completely safe approach though, as both events must be guaranteed to be delivered

**Pull request merged**
